services:
  formit.api:
    environment:
      - DBCONN=Host=postgres_db;Port=5432;Database=QuizApiDb;Username=postgres;Password=postgres
      - ADMIN_DEFAULT_EMAIL=admin@formit.com
      - ADMIN_DEFAULT_PASSWORD=Admin@123
      - JWT_SECRET_KEY=SuperSecretKey@345ThisIsALongKeyForSecurity!
      - JWT_EXPIRATION_HOURS=2
      - JWT_ISSUER=FormitApi
      - JWT_AUDIENCE=FormitClient
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    networks:
      - formit
    depends_on:
      - postgres_db

  formit.app:
    environment:
      - ApiSettings__BaseUrl=http://localhost:8080/ 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "8082:80"
    networks:
      - formit
    depends_on:
      - formit.api
      - postgres_db

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: QuizApiDb
    networks:
      - formit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  formit:  

