services:
  formit.api:
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    networks:
      - formit
    depends_on:
      - postgres_db

  formit.app:
    env_file:
      - .env
    ports:
      - "8082:80"
    networks:
      - formit
    depends_on:
      - formit.api
      - postgres_db

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: QuizApiDb
    networks:
      - formit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  formit:  

